version: "3.0"

services:
    itopic:
      image: pengbotao/itopic.go:alpine
      container_name: itopic
      restart: always
      ports:
        - 38001:8001
      working_dir: /www/itopic.go
      volumes:
        - G:/itopic.go/posts/:/www/itopic.go/posts
        - G:/itopic.go/static/:/www/itopic.go/static
      networks:
        - server
      entrypoint: /www/itopic.go/itopic -host 0.0.0.0:8001 -debug > /dev/null

networks:
  server:
     driver: bridge